# Generated by Django 3.2.8 on 2021-10-15 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='makanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemmakan', models.TextField(default='')),
                ('jenismakan', models.CharField(max_length=200)),
                ('jumlahmakan', models.IntegerField(default=0)),
                ('hargamakan', models.IntegerField()),
            ],
        ),
    ]
