# Generated by Django 3.2.8 on 2021-10-13 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='makanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.TextField(default='')),
                ('jenis', models.CharField(max_length=200)),
                ('jumlah', models.IntegerField()),
                ('harga', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='minuman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.TextField(default='')),
                ('jenis', models.CharField(max_length=200)),
                ('jumlah', models.IntegerField()),
                ('harga', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='pesanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah_makanan', models.IntegerField()),
                ('makanan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.makanan')),
                ('minuman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.minuman')),
            ],
        ),
    ]
