# Generated by Django 3.2.8 on 2021-10-15 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_minuman_pesanan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minuman',
            name='jumlahminum',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pesanan',
            name='jumlah_makanan',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pesanan',
            name='jumlah_minuman',
            field=models.IntegerField(default=0),
        ),
    ]
