# Generated by Django 3.2.8 on 2021-10-12 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20211012_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='harga',
        ),
        migrations.RemoveField(
            model_name='task',
            name='jenis',
        ),
        migrations.RemoveField(
            model_name='task',
            name='jumlah',
        ),
    ]
