# Generated by Django 3.2.8 on 2021-10-13 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_makanan_minuman_pesanan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makanan',
            name='jumlah',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='minuman',
            name='jumlah',
            field=models.IntegerField(max_length=10),
        ),
    ]
