# Generated by Django 3.2.8 on 2021-10-13 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_auto_20211013_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pesanan',
            name='makanan',
        ),
        migrations.RemoveField(
            model_name='pesanan',
            name='minuman',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='minuman',
        ),
        migrations.DeleteModel(
            name='pesanan',
        ),
    ]
