# Generated by Django 3.2.8 on 2021-10-13 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_auto_20211013_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='minuman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemminum', models.TextField(default='')),
                ('jenisminum', models.CharField(max_length=200)),
                ('jumlahminum', models.IntegerField(max_length=10)),
                ('hargaminum', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='makanan',
            old_name='harga',
            new_name='hargamakan',
        ),
        migrations.RenameField(
            model_name='makanan',
            old_name='item',
            new_name='itemmakan',
        ),
        migrations.RenameField(
            model_name='makanan',
            old_name='jenis',
            new_name='jenismakan',
        ),
        migrations.RenameField(
            model_name='makanan',
            old_name='jumlah',
            new_name='jumlahmakan',
        ),
    ]
