# Generated by Django 3.2.8 on 2021-10-13 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_auto_20211013_1539'),
    ]

    operations = [
        migrations.DeleteModel(
            name='minuman',
        ),
    ]
